<!doctype html>
<html lang="fa" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#071015"><meta name="robots" content="noindex,nofollow"><link rel="manifest" href="/admin.webmanifest"><link rel="icon" href="/denardi-icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/icons/apple-touch-icon.png"><title>Denardi Admin</title>@vite('resources/js/admin.js')</head>
<body class="admin-app dashboard-screen">
<aside class="admin-sidebar">
    <a class="admin-brand" href="/admin"><span>D</span><b>DENARDI</b></a>
    <nav aria-label="بخش‌های مدیریت">
        <button class="active" data-admin-target="overview">نمای کلی</button>
        <button data-admin-target="products">محصول‌ها <small>قیمت و موجودی</small></button>
        <button data-admin-target="categories">دسته‌ها</button>
        <button data-admin-target="content">صفحه‌ها و بلوک‌ها</button>
        <button data-admin-target="media">رسانه</button>
        <button data-admin-target="qr">QR و آمار</button>
        <button data-admin-target="settings">تنظیمات زبان</button>
    </nav>
    <button class="logout-button" data-logout>خروج</button>
</aside>
<main class="admin-main">
    <header class="admin-topbar"><div><p class="admin-kicker">DENARDI · OPERATIONS</p><h1 data-view-title>نمای کلی</h1></div><div class="admin-identity"><span data-business-name>—</span><b data-user-name>—</b></div></header>
    <div class="admin-loading" data-loading>در حال بارگذاری پنل…</div>
    <div data-dashboard hidden>
        <section data-admin-view="overview">
            <div class="metric-grid"><article><span>محصول‌ها</span><strong data-product-count>0</strong></article><article><span>دسته‌ها</span><strong data-category-count>0</strong></article><article><span>ترجمه‌ها</span><strong>FA · EN · AR</strong></article><article><span>شعبه فعال</span><strong data-branch-count>0</strong></article><article><span>QR فعال</span><strong data-qr-count>0</strong></article><article><span>اسکن ۳۰ روز</span><strong data-scan-count>0</strong></article><article><span>آخرین بکاپ</span><strong data-backup-status>—</strong></article></div>
            <section class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">WORKFLOW STATUS</p><h2>آمادگی مدیریت محتوا</h2></div></div><div class="readiness-summary" data-readiness-summary></div></section>
        </section>
        <section data-admin-view="products" hidden><div class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">DIGITAL MENU</p><h2>محصول‌ها، قیمت و موجودی</h2></div><button class="admin-button small" data-open-product>محصول جدید</button></div><div class="admin-table" data-products></div></div></section>
        <section data-admin-view="categories" hidden><div class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">MENU STRUCTURE</p><h2>دسته‌ها و ترتیب نمایش</h2></div></div><form class="category-form" data-category-form><input name="public_id" type="hidden"><div class="form-grid three"><label>شناسه URL<input name="slug" required placeholder="coffee"></label><label>دسته والد<select name="parent_id"><option value="">بدون والد</option></select></label><label class="checkbox"><input name="is_featured" type="checkbox"> ویژه</label></div><div data-category-translations class="translation-fields"></div><div class="form-actions"><button class="admin-button" type="submit">ذخیره دسته</button><button class="status" type="button" data-reset-category>فرم جدید</button></div></form><div class="admin-table" data-categories></div></div></section>
        <section data-admin-view="content" hidden><div class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">LOCALIZED CMS</p><h2>صفحه‌ها و بلوک‌ها</h2></div><button class="admin-button small" data-open-page>صفحه جدید</button></div><div class="admin-table page-table" data-pages></div></div></section>
        <section data-admin-view="media" hidden><div class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">MEDIA PIPELINE</p><h2>رسانه، WebP و Thumbnail</h2></div></div><form class="media-form" data-media-form><label>تصویر اصلی<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required></label><div data-media-translations class="translation-fields"></div><button class="admin-button" type="submit">بارگذاری و بهینه‌سازی</button></form><div class="media-grid" data-media></div></div></section>
        <section data-admin-view="qr" hidden><div class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">QR · ANALYTICS</p><h2>QR منو و میز</h2></div></div><form class="qr-form" data-qr-form><label>شعبه<select name="branch_id" required></select></label><label>نوع<select name="type"><option value="menu">منوی عمومی</option><option value="table">میز</option></select></label><label>عنوان<input name="label" required placeholder="ورودی اصلی"></label><label data-table-key hidden>شناسه میز<input name="table_key" placeholder="table-12"></label><button class="admin-button" type="submit">ساخت QR</button></form><div class="analytics-strip"><div><span>اسکن امروز</span><b data-scans-today>0</b></div><div><span>اسکن ۷ روز</span><b data-scans-week>0</b></div><div><span>اسکن ۳۰ روز</span><b data-scans-month>0</b></div><div><span>نمایش منو ۳۰ روز</span><b data-menu-views-month>0</b></div><div><span>نمایش دسته ۳۰ روز</span><b data-category-views-month>0</b></div><div><span>نمایش محصول ۳۰ روز</span><b data-product-views-month>0</b></div></div><div class="admin-table" data-qr-codes></div></div></section>
        <section data-admin-view="settings" hidden><div class="admin-panel"><div class="panel-title"><div><p class="admin-kicker">LOCALIZATION</p><h2>زبان‌های عمومی</h2></div></div><div class="locale-settings" data-locale-settings></div><p class="settings-note">فارسی زبان پیش‌فرض است. جهت رابط از metadata زبان تعیین می‌شود و محتوای ناقص بدون fallback خاموش منتشر نمی‌شود.</p></div></section>
    </div>
</main>
<dialog class="admin-dialog" data-product-dialog><form method="dialog" class="dialog-head"><h2 data-product-dialog-title>محصول جدید</h2><button aria-label="بستن">×</button></form><form data-product-form><input name="public_id" type="hidden"><label>دسته<select name="category_id" required></select></label><label>تصویر محصول<select name="primary_media_id"><option value="">بدون تصویر</option></select></label><label>شناسه URL<input name="slug" required placeholder="iced-latte"></label><div data-product-translations class="translation-fields"></div><div class="form-grid product-settings"><label>شعبه<select name="branch_id" required></select></label><label>قیمت شعبه (ریال)<input name="price_amount" type="number" min="0" required></label><label>انتشار<select name="publication_state"><option value="draft">پیش‌نویس</option><option value="published">منتشرشده</option><option value="inactive">غیرفعال</option><option value="archived">آرشیو</option></select></label><label>موجودی<select name="availability_state"><option value="available">موجود</option><option value="sold_out">ناموجود</option></select></label></div><div class="form-grid flags"><label class="checkbox"><input name="is_featured" type="checkbox"> ویژه</label><label class="checkbox"><input name="is_new" type="checkbox"> جدید</label><label class="checkbox"><input name="is_best_seller" type="checkbox"> پرفروش</label></div><p class="form-error" data-product-error hidden></p><button class="admin-button" type="submit">ذخیره محصول</button></form></dialog>
<dialog class="admin-dialog" data-page-dialog><form method="dialog" class="dialog-head"><h2 data-page-dialog-title>صفحه جدید</h2><button aria-label="بستن">×</button></form><form data-page-form><input name="public_id" type="hidden"><label>شناسه URL<input name="slug" required placeholder="about"></label><label>قالب<input name="template" value="standard" required></label><div data-page-translations class="translation-fields"></div><p class="form-error" data-page-error hidden></p><button class="admin-button" type="submit">ذخیره صفحه</button></form></dialog>
<dialog class="admin-dialog" data-block-dialog><form method="dialog" class="dialog-head"><h2 data-block-dialog-title>بلوک محتوای جدید</h2><button aria-label="بستن">×</button></form><form data-block-form><input name="page_id" type="hidden"><input name="block_id" type="hidden"><label>نوع بلوک<select name="type" required></select></label><label data-position-field>جایگاه<input name="position" type="number" min="0" value="0" required></label><label class="checkbox"><input name="is_enabled" type="checkbox" checked> فعال</label><div class="schema-fields"><section><h3>تنظیمات مشترک</h3><div data-block-structure></div></section><section><h3>محتوای مستقل FA/EN/AR</h3><div data-block-translations class="translation-fields"></div></section></div><p class="form-error" data-block-error hidden></p><button class="admin-button" type="submit">ذخیره بلوک</button></form></dialog>
<dialog class="admin-dialog" data-media-dialog><form method="dialog" class="dialog-head"><h2>اطلاعات رسانه</h2><button aria-label="بستن">×</button></form><form data-media-edit-form><input name="media_id" type="hidden"><div data-media-edit-translations class="translation-fields"></div><p class="form-error" data-media-error hidden></p><button class="admin-button" type="submit">ذخیره اطلاعات</button></form></dialog>
<div class="toast" data-toast hidden></div>
</body>
</html>
